version: "3.9"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
      - ./.env

  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./.env

  web:
    build: ./web
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - server
    volumes:
      - ./web:/app
      - /app/node_modules
    env_file:
      - ./.env
