FROM node:14.17-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . ./

EXPOSE ${REACT_APP_SERVER_PORT}
EXPOSE ${REACT_APP_SOCKET_PORT}

CMD [ "yarn", "dev" ]