FROM node:14.17-alpine AS build

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . ./
RUN yarn build

FROM nginx:1.21-alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE ${PORT}

CMD [ "nginx", "-g", "daemon off;" ]
